parameters:
    asoc_compassomator.bundle_finder.class: Asoc\CompassomatorBundle\Compassomator\BundleFinder
    asoc_compassomator.process_manager.class: Asoc\CompassomatorBundle\Compassomator\ProcessManager
    asoc_compassomator.process_manager.run_dir: %kernel.cache_dir%/../compassomator
    asoc_compassomator.process_runner.class: Asoc\CompassomatorBundle\Compassomator\ProcessRunner
    asoc_compassomator.cache_clearer.class: Asoc\CompassomatorBundle\CacheClearer\CacheClearer

services:
    asoc_compassomator.cache_clearer:
        class: %asoc_compassomator.cache_clearer.class%
        arguments:
            - @asoc_compassomator.process_runner
        tags:
            - { name: kernel.cache_clearer }
    asoc_compassomator.process_manager:
        class: %asoc_compassomator.process_manager.class%
        arguments:
            - %asoc_compassomator.process_manager.run_dir%
    asoc_compassomator.process_runner:
        class: %asoc_compassomator.process_runner.class%
        arguments:
            - @asoc_compassomator.bundle_finder
            - @asoc_compassomator.process_manager
            - %asoc_compassomator.process_runner.manage_assetic%
            - %kernel.environment%
    asoc_compassomator.bundle_finder:
        class: %asoc_compassomator.bundle_finder.class%
        arguments:
            - @kernel
            - @filesystem
            - %asoc_compassomator.bundle_finder.config_rb_dir%
            - %asoc_compassomator.bundle_finder.config_rb_name%
            - %asoc_compassomator.bundle_finder.bundles_dir%
            - %asoc_compassomator.bundle_finder.assetic_css_root%